
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/package
      - app_data:/var/www
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite

volumes:
  app_data: